# Python Crash Course

## Basic data types

### Numbers

In [1]:
x=3
print type(x)

<type 'int'>


In [2]:
print x

3


In [3]:
print x+1

4


In [4]:
print x-1

2


In [5]:
print x*2

6


In [6]:
print x**2

9


In [7]:
x += 1
print x

4


In [8]:
x *= 2
print x

8


In [9]:
y = 3.2
print type(y)

<type 'float'>


In [10]:
print y, y+1, y*2, y**2

3.2 4.2 6.4 10.24


### Booleans

In [11]:
t = True
f = False
print type(t)

<type 'bool'>


In [12]:
print t and f

False


In [13]:
print t or f

True


In [14]:
print not t

False


In [15]:
print t != f

True


### Strings

In [16]:
hello = 'hello'
world = 'world'
print hello

hello


In [17]:
print len(hello)

5


In [18]:
hw = hello + ' ' + world
print hw

hello world


In [19]:
hw12 = '%s %s %d' % (hello, world, 12)
print hw12

hello world 12


In [20]:
s = "hello"
print s.capitalize()

Hello


In [21]:
print s.upper()

HELLO


In [22]:
print s.rjust(7) #right-justify

  hello


In [23]:
print s.center(7)

 hello 


In [24]:
print s.replace('l',"(ell)")

he(ell)(ell)o


In [25]:
print '   world '.strip() #strip leading and trailing whitespace

world


## Containers

### Lists

In [26]:
xs = [3,1,2]
print xs, xs[2]

[3, 1, 2] 2


In [27]:
print xs[-1]

2


In [28]:
xs[2] = 'foo'
print xs

[3, 1, 'foo']


In [29]:
xs.append('bar')
print xs

[3, 1, 'foo', 'bar']


In [30]:
x=xs.pop()
print x,xs

bar [3, 1, 'foo']


- Slicing

In [31]:
nums = range(5)
print nums

[0, 1, 2, 3, 4]


In [32]:
print nums[2:4]

[2, 3]


In [33]:
print nums[2:]

[2, 3, 4]


In [34]:
print nums[:2]

[0, 1]


In [35]:
print nums[:]

[0, 1, 2, 3, 4]


In [36]:
print nums[:-1]

[0, 1, 2, 3]


In [37]:
nums[2:4] = [8,9]
print nums

[0, 1, 8, 9, 4]


- Loops

In [41]:
animals = ['cat','dog','monkey']
for animal in animals:
    print animal

cat
dog
monkey


In [42]:
for idx, animal in enumerate(animals):
    print '#%d: %s' % (idx+1, animal)

#1: cat
#2: dog
#3: monkey


- List comprehensions

In [44]:
nums = [0,1,2,3,4]
squares = [x**2 for x in nums]
print squares

[0, 1, 4, 9, 16]


In [46]:
even_squares = [x**2 for x in nums if x%2 == 0]
print even_squares

[0, 4, 16]


### Dictionaries

In [47]:
d = {'cat':'cute', 'dog':'furry'}
print d['cat']

cute


In [48]:
print 'cat' in d

True


In [49]:
d['fish']='wet'
print d['fish']

wet


In [50]:
print d.get('monkey','N/A')

N/A


In [51]:
print d.get('fish','N/A')

wet


In [52]:
del d['fish']

In [53]:
print d.get('fish', 'N/A')

N/A


- Loops

In [54]:
d = {'person':2,'cat':4,'spider':8}
for animal in d:
    legs = d[animal]
    print 'A %s has %d legs' % (animal,legs)

A person has 2 legs
A spider has 8 legs
A cat has 4 legs


In [56]:
for animal,legs in d.iteritems():
    print 'A %s has %d legs' % (animal,legs)

A person has 2 legs
A spider has 8 legs
A cat has 4 legs


- Dictionary comprehensions

In [57]:
nums = [0,1,2,3,4]
even_num_to_square = {x:x**2 for x in nums if x%2==0}
print even_num_to_square

{0: 0, 2: 4, 4: 16}


### Sets

In [58]:
animals = {'cat','dog'}
print 'cat' in animals

True


In [59]:
print 'fish' in animals

False


In [60]:
animals.add('fish')
print 'fish' in animals

True


In [61]:
print len(animals)

3


In [62]:
animals.add('cat')
print len(animals)

3


In [63]:
animals.remove('cat')
print len(animals)

2


- Loops

In [64]:
animals = {'cat','dog','fish'}
for idx,animal in enumerate(animals):
    print '#%d: %s' % (idx+1, animal)

#1: fish
#2: dog
#3: cat


- Set comprehensions

In [65]:
from math import sqrt
nums = {int(sqrt(x)) for x in range(30)}
print nums

set([0, 1, 2, 3, 4, 5])


### Tuples

In [71]:
d = {(x,x+1): x for x in range(10)}
t = (5,6)
print type(t)

<type 'tuple'>


In [72]:
d

{(0, 1): 0,
 (1, 2): 1,
 (2, 3): 2,
 (3, 4): 3,
 (4, 5): 4,
 (5, 6): 5,
 (6, 7): 6,
 (7, 8): 7,
 (8, 9): 8,
 (9, 10): 9}

In [67]:
print d[t]

5


In [68]:
print d[(1,2)]

1


## Functions

In [73]:
def sign(x):
    if x>0:
        return 'positive'
    elif x<0:
        return 'negative'
    else:
        return 'zero'

In [74]:
for x in [-1,0,1]:
    print sign(x)

negative
zero
positive


In [75]:
def hello(name, loud=False):
    if loud:
        print 'HELLO, %s!' % name.upper()
    else:
        print 'Hello, %s' % name

In [76]:
hello('Bob')

Hello, Bob


In [77]:
hello('Fred',loud=True)

HELLO, FRED!


## Classes

In [79]:
class Greeter(object):
    def __init__(self,name):
        self.name=name
    def greet(self,loud=False):
        if loud:
            print 'HELLO, %s!' % self.name.upper()
        else:
            print 'Hello, %s' % self.name
g=Greeter('Fred')
g.greet()

Hello, Fred


In [80]:
g.greet(loud=True)

HELLO, FRED!


## Numpy

### Arrays

In [81]:
import numpy as np

In [82]:
a = np.array([1,2,3])
print type(a)

<type 'numpy.ndarray'>


In [83]:
print a.shape

(3,)


In [84]:
print a[0],a[1],a[2]

1 2 3


In [85]:
a[0]=5
print a

[5 2 3]


In [86]:
b=np.array([[1,2,3],[4,5,6]])
print b.shape
print b[0,0], b[0,1], b[1,0]

(2, 3)
1 2 4


In [88]:
a = np.zeros((2,2))
print a

[[ 0.  0.]
 [ 0.  0.]]


In [89]:
b = np.ones((1,2))
print b

[[ 1.  1.]]


In [90]:
c = np.full((2,2),7)
print c

[[ 7.  7.]
 [ 7.  7.]]


/home/phc7065/.local/lib/python2.7/site-packages/numpy/core/numeric.py:301: FutureWarning: in the future, full((2, 2), 7) will return an array of dtype('int64')
  format(shape, fill_value, array(fill_value).dtype), FutureWarning)


In [91]:
d = np.eye(2)
print d

[[ 1.  0.]
 [ 0.  1.]]


In [92]:
e = np.random.random((2,2))
print e

[[ 0.13561479  0.1672848 ]
 [ 0.51250832  0.57494467]]


### Array indexing

- Slicing

In [93]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [94]:
b=a[:2,1:3]

In [95]:
print a[0,1]

2


In [96]:
b[0,0]= 77
print a[0,1]

77


In [97]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [98]:
row_r1 = a[1,:]
row_r2 = a[1:2,:]
print row_r1,row_r1.shape

[5 6 7 8] (4,)


In [99]:
print row_r2,row_r2.shape

[[5 6 7 8]] (1, 4)


In [101]:
col_r1 = a[:,1]
col_r2 = a[:,1:2]
print col_r1, col_r1.shape

[ 2  6 10] (3,)


In [102]:
print col_r2, col_r2.shape

[[ 2]
 [ 6]
 [10]] (3, 1)


### Integer array indexing