# Python Crash Course

## Basic data types

### Numbers

In [1]:
x=3
print type(x)

<type 'int'>


In [2]:
print x

3


In [3]:
print x+1

4


In [4]:
print x-1

2


In [5]:
print x*2

6


In [6]:
print x**2

9


In [7]:
x += 1
print x

4


In [8]:
x *= 2
print x

8


In [9]:
y = 3.2
print type(y)

<type 'float'>


In [10]:
print y, y+1, y*2, y**2

3.2 4.2 6.4 10.24


### Booleans

In [11]:
t = True
f = False
print type(t)

<type 'bool'>


In [12]:
print t and f

False


In [13]:
print t or f

True


In [14]:
print not t

False


In [15]:
print t != f

True


### Strings

In [16]:
hello = 'hello'
world = 'world'
print hello

hello


In [17]:
print len(hello)

5


In [18]:
hw = hello + ' ' + world
print hw

hello world


In [19]:
hw12 = '%s %s %d' % (hello, world, 12)
print hw12

hello world 12


In [20]:
s = "hello"
print s.capitalize()

Hello


In [21]:
print s.upper()

HELLO


In [22]:
print s.rjust(7) #right-justify

  hello


In [23]:
print s.center(7)

 hello 


In [24]:
print s.replace('l',"(ell)")

he(ell)(ell)o


In [25]:
print '   world '.strip() #strip leading and trailing whitespace

world


## Containers

### Lists

In [26]:
xs = [3,1,2]
print xs, xs[2]

[3, 1, 2] 2


In [27]:
print xs[-1]

2


In [28]:
xs[2] = 'foo'
print xs

[3, 1, 'foo']


In [29]:
xs.append('bar')
print xs

[3, 1, 'foo', 'bar']


In [30]:
x=xs.pop()
print x,xs

bar [3, 1, 'foo']


- Slicing

In [31]:
nums = range(5)
print nums

[0, 1, 2, 3, 4]


In [32]:
print nums[2:4]

[2, 3]


In [33]:
print nums[2:]

[2, 3, 4]


In [34]:
print nums[:2]

[0, 1]


In [35]:
print nums[:]

[0, 1, 2, 3, 4]


In [36]:
print nums[:-1]

[0, 1, 2, 3]


In [37]:
nums[2:4] = [8,9]
print nums

[0, 1, 8, 9, 4]


- Loops

In [38]:
animals = ['cat','dog','monkey']
for animal in animals:
    print animal

cat
dog
monkey


In [39]:
for idx, animal in enumerate(animals):
    print '#%d: %s' % (idx+1, animal)

#1: cat
#2: dog
#3: monkey


- List comprehensions

In [40]:
nums = [0,1,2,3,4]
squares = [x**2 for x in nums]
print squares

[0, 1, 4, 9, 16]


In [41]:
even_squares = [x**2 for x in nums if x%2 == 0]
print even_squares

[0, 4, 16]


### Dictionaries

In [42]:
d = {'cat':'cute', 'dog':'furry'}
print d['cat']

cute


In [43]:
print 'cat' in d

True


In [44]:
d['fish']='wet'
print d['fish']

wet


In [45]:
print d.get('monkey','N/A')

N/A


In [46]:
print d.get('fish','N/A')

wet


In [47]:
del d['fish']

In [48]:
print d.get('fish', 'N/A')

N/A


- Loops

In [49]:
d = {'person':2,'cat':4,'spider':8}
for animal in d:
    legs = d[animal]
    print 'A %s has %d legs' % (animal,legs)

A person has 2 legs
A spider has 8 legs
A cat has 4 legs


In [50]:
for animal,legs in d.iteritems():
    print 'A %s has %d legs' % (animal,legs)

A person has 2 legs
A spider has 8 legs
A cat has 4 legs


- Dictionary comprehensions

In [51]:
nums = [0,1,2,3,4]
even_num_to_square = {x:x**2 for x in nums if x%2==0}
print even_num_to_square

{0: 0, 2: 4, 4: 16}


### Sets

In [52]:
animals = {'cat','dog'}
print 'cat' in animals

True


In [53]:
print 'fish' in animals

False


In [54]:
animals.add('fish')
print 'fish' in animals

True


In [55]:
print len(animals)

3


In [56]:
animals.add('cat')
print len(animals)

3


In [57]:
animals.remove('cat')
print len(animals)

2


- Loops

In [58]:
animals = {'cat','dog','fish'}
for idx,animal in enumerate(animals):
    print '#%d: %s' % (idx+1, animal)

#1: fish
#2: dog
#3: cat


- Set comprehensions

In [59]:
from math import sqrt
nums = {int(sqrt(x)) for x in range(30)}
print nums

set([0, 1, 2, 3, 4, 5])


### Tuples

In [60]:
d = {(x,x+1): x for x in range(10)}
t = (5,6)
print type(t)

<type 'tuple'>


In [61]:
d

{(0, 1): 0,
 (1, 2): 1,
 (2, 3): 2,
 (3, 4): 3,
 (4, 5): 4,
 (5, 6): 5,
 (6, 7): 6,
 (7, 8): 7,
 (8, 9): 8,
 (9, 10): 9}

In [62]:
print d[t]

5


In [63]:
print d[(1,2)]

1


## Functions

In [64]:
def sign(x):
    if x>0:
        return 'positive'
    elif x<0:
        return 'negative'
    else:
        return 'zero'

In [65]:
for x in [-1,0,1]:
    print sign(x)

negative
zero
positive


In [66]:
def hello(name, loud=False):
    if loud:
        print 'HELLO, %s!' % name.upper()
    else:
        print 'Hello, %s' % name

In [67]:
hello('Bob')

Hello, Bob


In [68]:
hello('Fred',loud=True)

HELLO, FRED!


## Classes

In [69]:
class Greeter(object):
    def __init__(self,name):
        self.name=name
    def greet(self,loud=False):
        if loud:
            print 'HELLO, %s!' % self.name.upper()
        else:
            print 'Hello, %s' % self.name
g=Greeter('Fred')
g.greet()

Hello, Fred


In [70]:
g.greet(loud=True)

HELLO, FRED!


## Numpy

### Arrays

In [71]:
import numpy as np

In [72]:
a = np.array([1,2,3])
print type(a)

<type 'numpy.ndarray'>


In [73]:
print a.shape

(3,)


In [74]:
print a[0],a[1],a[2]

1 2 3


In [75]:
a[0]=5
print a

[5 2 3]


In [76]:
b=np.array([[1,2,3],[4,5,6]])
print b.shape
print b[0,0], b[0,1], b[1,0]

(2, 3)
1 2 4


In [77]:
a = np.zeros((2,2))
print a

[[ 0.  0.]
 [ 0.  0.]]


In [78]:
b = np.ones((1,2))
print b

[[ 1.  1.]]


In [79]:
c = np.full((2,2),7)
print c

[[ 7.  7.]
 [ 7.  7.]]


/usr/local/lib/python2.7/site-packages/numpy/core/numeric.py:301: FutureWarning: in the future, full((2, 2), 7) will return an array of dtype('int64')
  format(shape, fill_value, array(fill_value).dtype), FutureWarning)


In [80]:
d = np.eye(2)
print d

[[ 1.  0.]
 [ 0.  1.]]


In [81]:
e = np.random.random((2,2))
print e

[[ 0.03818308  0.89755362]
 [ 0.78184636  0.31762038]]


### Array indexing

- Slicing

In [82]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [83]:
b=a[:2,1:3]

In [84]:
print a[0,1]

2


In [85]:
b[0,0]= 77
print a[0,1]

77


In [86]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [87]:
row_r1 = a[1,:]
row_r2 = a[1:2,:]
print row_r1,row_r1.shape

[5 6 7 8] (4,)


In [88]:
print row_r2,row_r2.shape

[[5 6 7 8]] (1, 4)


In [89]:
col_r1 = a[:,1]
col_r2 = a[:,1:2]
print col_r1, col_r1.shape

[ 2  6 10] (3,)


In [90]:
print col_r2, col_r2.shape

[[ 2]
 [ 6]
 [10]] (3, 1)


### Integer array indexing

In [91]:
a = np.array([[1,2], [3, 4], [5, 6]])
print a[[0, 1, 2], [0, 1, 0]]

[1 4 5]


In [92]:
print np.array([a[0, 0], a[1, 1], a[2, 0]]) 

[1 4 5]


In [93]:
print a[[0, 0], [1, 1]]

[2 2]


In [94]:
print np.array([a[0, 1], a[0, 1]])

[2 2]


In [95]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print a 

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [96]:
b = np.array([0, 2, 0, 1])
print a[np.arange(4), b]

[ 1  6  7 11]


In [97]:
a[np.arange(4), b] += 10
print a 

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [98]:
a = np.array([[1,2], [3, 4], [5, 6]])
bool_idx = (a > 2) 
print bool_idx 

[[False False]
 [ True  True]
 [ True  True]]


In [99]:
print a[bool_idx]

[3 4 5 6]


In [100]:
print a[a > 2]  

[3 4 5 6]


### Datatypes

In [101]:
x = np.array([1, 2])  # Let numpy choose the datatype
print x.dtype         # Prints "int64"

int64


In [102]:
x = np.array([1.0, 2.0])  # Let numpy choose the datatype
print x.dtype             # Prints "float64"

float64


In [103]:
x = np.array([1, 2], dtype=np.int64)  # Force a particular datatype
print x.dtype                         # Prints "int64"

int64


### Array math

In [104]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print x + y

[[  6.   8.]
 [ 10.  12.]]


In [105]:
print np.add(x, y)

[[  6.   8.]
 [ 10.  12.]]


In [106]:
print x - y

[[-4. -4.]
 [-4. -4.]]


In [107]:
print np.subtract(x, y)

[[-4. -4.]
 [-4. -4.]]


In [108]:
print x * y

[[  5.  12.]
 [ 21.  32.]]


In [109]:
print np.multiply(x, y)

[[  5.  12.]
 [ 21.  32.]]


In [110]:
print x / y

[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]


In [111]:
print np.sqrt(x)

[[ 1.          1.41421356]
 [ 1.73205081  2.        ]]


In [112]:
v = np.array([9,10])
w = np.array([11, 12])

In [113]:
print v.dot(w)

219


In [114]:
print np.dot(v, w)

219


In [115]:
print x.dot(v)

[ 29.  67.]


In [116]:
print np.dot(x, v)

[ 29.  67.]


In [117]:
print x.dot(y)

[[ 19.  22.]
 [ 43.  50.]]


In [118]:
print np.dot(x, y)

[[ 19.  22.]
 [ 43.  50.]]


In [119]:
x = np.array([[1,2],[3,4]])
print np.sum(x)  # Compute sum of all elements; prints "10"

10


In [120]:
print np.sum(x, axis=0)  # Compute sum of each column; prints "[4 6]"

[4 6]


In [121]:
print np.sum(x, axis=1)  # Compute sum of each row; prints "[3 7]"

[3 7]


In [122]:
x = np.array([[1,2], [3,4]])
print x

[[1 2]
 [3 4]]


In [123]:
print x.T

[[1 3]
 [2 4]]


In [124]:
v = np.array([1,2,3])
print v
print v.T 

[1 2 3]
[1 2 3]


### Broadcasting

In [125]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

In [126]:
for i in range(4):
    y[i, :] = x[i, :] + v
print y

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [127]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))  # Stack 4 copies of v on top of each other
print vv 

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [128]:
y = x + vv  # Add x and vv elementwise
print y

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [129]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print y

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [130]:
# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:
# [[ 4  5]
#  [ 8 10]
#  [12 15]]
print np.reshape(v, (3, 1)) * w

[[ 4  5]
 [ 8 10]
 [12 15]]


In [131]:
# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:
# [[2 4 6]
#  [5 7 9]]
print x + v

[[2 4 6]
 [5 7 9]]


In [132]:
# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:
# [[ 5  6  7]
#  [ 9 10 11]]
print (x.T + w).T

[[ 5  6  7]
 [ 9 10 11]]


In [133]:
# Another solution is to reshape w to be a row vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print x + np.reshape(w, (2, 1))

[[ 5  6  7]
 [ 9 10 11]]


In [134]:
# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
# [[ 2  4  6]
#  [ 8 10 12]]
print x * 2

[[ 2  4  6]
 [ 8 10 12]]


## Matplotlib

### Plotting

In [135]:
import matplotlib.pyplot as plt

In [136]:
x = np.arange(0, 3 * np.pi, 0.1)
y = np.sin(x)

In [137]:
plt.plot(x, y)
plt.show()

In [138]:
x = np.arange(0, 3 * np.pi, 0.1)
y_sin = np.sin(x)
y_cos = np.cos(x)

In [139]:
# Plot the points using matplotlib
plt.plot(x, y_sin)
plt.plot(x, y_cos)
plt.xlabel('x axis label')
plt.ylabel('y axis label')
plt.title('Sine and Cosine')
plt.legend(['Sine', 'Cosine'])
plt.show()

### Subplots

In [140]:
x = np.arange(0, 3 * np.pi, 0.1)
y_sin = np.sin(x)
y_cos = np.cos(x)

In [141]:
plt.subplot(2, 1, 1)

In [142]:
# Make the first plot
plt.plot(x, y_sin)
plt.title('Sine')

In [143]:
# Set the second subplot as active, and make the second plot.
plt.subplot(2, 1, 2)
plt.plot(x, y_cos)
plt.title('Cosine')

In [144]:
# Show the figure.
plt.show()

## Pandas

In [145]:
import pandas as pd

### Series

In [146]:
myarray = np.array([1, 2, 3])
rownames = ['a', 'b', 'c']
myseries = pd.Series(myarray, index=rownames)
print(myseries)

a    1
b    2
c    3
dtype: int64


In [147]:
print(myseries[0])
print(myseries['a'])

1
1


### Data Frames

In [148]:
myarray = np.array([[1, 2, 3], [4, 5, 6]])
rownames = ['a', 'b']
colnames = ['one', 'two', 'three']
mydataframe = pd.DataFrame(myarray, index=rownames, columns=colnames)
print(mydataframe)

   one  two  three
a    1    2      3
b    4    5      6


In [149]:
print("one column: %s") % mydataframe['one']
print("one column: %s") % mydataframe.one

one column: a    1
b    4
Name: one, dtype: int64
one column: a    1
b    4
Name: one, dtype: int64


### Download PIMA Indians Diabetes dataset and import as a Pandas dataframe

In [150]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/pima-indians-diabetes/pima-indians-diabetes.data"
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
dataset = pd.read_csv(url, names=names)

In [151]:
print(dataset.head(10))

   preg  plas  pres  skin  test  mass   pedi  age  class
0     6   148    72    35     0  33.6  0.627   50      1
1     1    85    66    29     0  26.6  0.351   31      0
2     8   183    64     0     0  23.3  0.672   32      1
3     1    89    66    23    94  28.1  0.167   21      0
4     0   137    40    35   168  43.1  2.288   33      1
5     5   116    74     0     0  25.6  0.201   30      0
6     3    78    50    32    88  31.0  0.248   26      1
7    10   115     0     0     0  35.3  0.134   29      0
8     2   197    70    45   543  30.5  0.158   53      1
9     8   125    96     0     0   0.0  0.232   54      1
